### Uses SQLAlchemy to answer Questions 1,4,5,8,9,10.
"""
SQL Queries to answer the following questions:
All count in whole number
ALL percentages, GPA, GRE quant, GRE verbal, and GRE analytical scores in 2 DECIMAL PLACES

1. How many entries in your database are from applicants who applied for Fall 2026?
4. What is the Average GPA of American applicants who applied for Fall 2026?
5. WHat percentage of Fall 2025 entries are acceptances?
8. How many Fall 2026 entries are acceptances from applicants applying for a PhD in Computer Science at Georgetown University, MIT, Stanford, and Carnegie Mellon?
9. Identify universities and programs LLM generated terms. Report Question 8 and Question 9 count for term, degree, and admissions status. Report the difference between them
10. What percentage of students getting accepted at NYU master's program are international?
"""

from sqlalchemy import Numeric, and_, cast, func, or_, select
from sqlalchemy.orm import Session

from models import Applicant, SessionLocal


### Include both common raw-text names for MIT because the original data varies.
raw_university_conditions = or_(
    Applicant.program.ilike("%Georgetown University%"),
    Applicant.program.ilike("%MIT%"),
    Applicant.program.ilike("%Massachusetts Institute of Technology%"),
    Applicant.program.ilike("%Stanford University%"),
    Applicant.program.ilike("%Carnegie Mellon University%"),
)


### Use the standardized university names generated by the LLM.
llm_university_conditions = or_(
    func.lower(Applicant.llm_generated_university)
    == "georgetown university",
    func.lower(Applicant.llm_generated_university)
    == "massachusetts institute of technology",
    func.lower(Applicant.llm_generated_university)
    == "stanford university",
    func.lower(Applicant.llm_generated_university)
    == "carnegie mellon university",
)


def question_1(session: Session) -> int:
    """Count applicants who applied for the Fall 2026 term."""

    statement = (
        select(func.count(Applicant.p_id))
        .where(Applicant.term == "Fall 2026")
    )

    return session.scalar(statement) or 0


def question_4(session: Session):
    """Find the average GPA of American Fall 2026 applicants."""

    # PostgreSQL needs NUMERIC before ROUND can use two decimal places.
    rounded_average = func.round(
        cast(func.avg(Applicant.gpa), Numeric),
        2,
    )

    statement = select(rounded_average).where(
        and_(
            Applicant.term == "Fall 2026",
            Applicant.us_or_international == "American",
            Applicant.gpa.is_not(None),
        )
    )

    return session.scalar(statement)


def question_5(session: Session):
    """Calculate the acceptance percentage for Fall 2025 entries."""

    total_statement = (
        select(func.count(Applicant.p_id))
        .where(Applicant.term == "Fall 2025")
    )
    accepted_statement = select(func.count(Applicant.p_id)).where(
        and_(
            Applicant.term == "Fall 2025",
            Applicant.status == "Accepted",
        )
    )

    total_count = session.scalar(total_statement) or 0
    accepted_count = session.scalar(accepted_statement) or 0

    # Avoid dividing by zero if no Fall 2025 rows exist.
    if total_count == 0:
        return None

    return round(100 * accepted_count / total_count, 2)


def question_8(session: Session) -> int:
    """Count qualifying applicants by searching the original program text."""

    statement = select(func.count(Applicant.p_id)).where(
        and_(
            Applicant.term == "Fall 2026",
            Applicant.degree == "PhD",
            Applicant.status == "Accepted",
            Applicant.program.ilike("%computer science%"),
            raw_university_conditions,
        )
    )

    return session.scalar(statement) or 0


def question_9(session: Session) -> int:
    """Count the same applicants using exact LLM-standardized fields."""

    statement = select(func.count(Applicant.p_id)).where(
        and_(
            Applicant.term == "Fall 2026",
            Applicant.degree == "PhD",
            Applicant.status == "Accepted",
            func.lower(Applicant.llm_generated_program)
            == "computer science",
            llm_university_conditions,
        )
    )

    return session.scalar(statement) or 0


def question_10(session: Session):
    """Find the international percentage for accepted NYU master's rows."""

    accepted_nyu_masters = and_(
        Applicant.status == "Accepted",
        func.lower(Applicant.llm_generated_university)
        == "new york university",
        Applicant.degree.ilike("Master%"),
    )

    total_statement = select(func.count(Applicant.p_id)).where(
        accepted_nyu_masters
    )
    international_statement = select(func.count(Applicant.p_id)).where(
        and_(
            accepted_nyu_masters,
            Applicant.us_or_international == "International",
        )
    )

    total_count = session.scalar(total_statement) or 0
    international_count = session.scalar(international_statement) or 0

    # Avoid dividing by zero if no matching NYU rows exist.
    if total_count == 0:
        return None

    return round(100 * international_count / total_count, 2)


def format_decimal(value, suffix=""):
    """Display missing results clearly and numeric results to two places."""

    if value is None:
        return "N/A"

    return f"{value:.2f}{suffix}"


def main():
    """Open one session and run the requested ORM questions in order."""

    with SessionLocal() as session:
        fall_2026_count = question_1(session)
        american_average_gpa = question_4(session)
        fall_2025_acceptance_percentage = question_5(session)
        raw_text_count = question_8(session)
        llm_standardized_count = question_9(session)
        nyu_international_percentage = question_10(session)

    count_difference = llm_standardized_count - raw_text_count

    print(f"1. Fall 2026 applicant count: {fall_2026_count}")
    print(
        "4. American Fall 2026 average GPA: "
        f"{format_decimal(american_average_gpa)}"
    )
    print(
        "5. Fall 2025 acceptance percentage: "
        f"{format_decimal(fall_2025_acceptance_percentage, '%')}"
    )
    print(f"8. Raw-text match count: {raw_text_count}")
    print(f"9. LLM-standardized match count: {llm_standardized_count}")
    print(f"   LLM count minus raw-text count: {count_difference}")
    print(
        "10. International percentage among accepted NYU master's "
        f"applicants: {format_decimal(nyu_international_percentage, '%')}"
    )


if __name__ == "__main__":
    main()
