"""Answer GradCafe analysis questions 1, 4, 5, 8, 9, and 10 with SQLAlchemy.

Counts are whole numbers. Percentages and scores display two decimal places.
Questions 8 and 9 compare accepted Fall 2026 Computer Science PhD applicants
at Georgetown, MIT, Stanford, and Carnegie Mellon using raw and LLM fields.
"""

from sqlalchemy import Numeric, and_, cast, func, or_, select
from sqlalchemy.orm import Session
from sqlalchemy.sql.functions import count

from .models import Applicant, session_local
from .query_limits import MAX_QUERY_LIMIT, clamp_query_limit

### Include both common raw-text names for MIT because the original data varies.
raw_university_conditions = or_(
    Applicant.program.ilike("%Georgetown University%"),
    Applicant.program.ilike("%MIT%"),
    Applicant.program.ilike("%Massachusetts Institute of Technology%"),
    Applicant.program.ilike("%Stanford University%"),
    Applicant.program.ilike("%Carnegie Mellon University%"))

### Use the standardized university names generated by the LLM.
llm_university_conditions = or_(
    func.lower(Applicant.llm_generated_university)
    == "georgetown university",
    func.lower(Applicant.llm_generated_university)
    == "massachusetts institute of technology",
    func.lower(Applicant.llm_generated_university)
    == "stanford university",
    func.lower(Applicant.llm_generated_university)
    == "carnegie mellon university")

def question_1(session: Session, limit=MAX_QUERY_LIMIT) -> int:
    """Count applicants who applied for the Fall 2026 term."""

    statement = (
        select(count(Applicant.p_id))
        .where(Applicant.term == "Fall 2026"))

    statement = statement.limit(clamp_query_limit(limit))
    return session.scalar(statement) or 0

def question_4(session: Session, limit=MAX_QUERY_LIMIT):
    """Find the average GPA of American Fall 2026 applicants."""

    # PostgreSQL needs NUMERIC before ROUND can use two decimal places.
    rounded_average = func.round(
        cast(func.avg(Applicant.gpa), Numeric),2)

    statement = select(rounded_average).where(
        and_(Applicant.term == "Fall 2026",
            Applicant.us_or_international == "American",
            Applicant.gpa.is_not(None)))

    statement = statement.limit(clamp_query_limit(limit))
    return session.scalar(statement)

def question_5(session: Session, limit=MAX_QUERY_LIMIT):
    """Calculate the acceptance percentage for Fall 2025 entries."""

    total_statement = (select(count(Applicant.p_id))
        .where(Applicant.term == "Fall 2025"))
    accepted_statement = select(count(Applicant.p_id)).where(
        and_(Applicant.term == "Fall 2025",
            Applicant.status == "Accepted"))

    total_statement = total_statement.limit(clamp_query_limit(limit))
    total_count = session.scalar(total_statement) or 0
    accepted_statement = accepted_statement.limit(clamp_query_limit(limit))
    accepted_count = session.scalar(accepted_statement) or 0

    # Avoid dividing by zero if no Fall 2025 rows exist.
    if total_count == 0:
        return None
    return round(100 * accepted_count / total_count, 2)

def question_8(session: Session, limit=MAX_QUERY_LIMIT) -> int:
    """Count qualifying applicants by searching the original program text."""

    statement = select(count(Applicant.p_id)).where(
        and_(Applicant.term == "Fall 2026",
            Applicant.degree == "PhD",
            Applicant.status == "Accepted",
            Applicant.program.ilike("%computer science%"),
            raw_university_conditions))

    statement = statement.limit(clamp_query_limit(limit))
    return session.scalar(statement) or 0

def question_9(session: Session, limit=MAX_QUERY_LIMIT) -> int:
    """Count the same applicants using exact LLM-standardized fields."""

    statement = select(count(Applicant.p_id)).where(
        and_(Applicant.term == "Fall 2026",
            Applicant.degree == "PhD",
            Applicant.status == "Accepted",
            func.lower(Applicant.llm_generated_program)
            == "computer science",
            llm_university_conditions))

    statement = statement.limit(clamp_query_limit(limit))
    return session.scalar(statement) or 0

def question_10(session: Session, limit=MAX_QUERY_LIMIT):
    """Find the international percentage for accepted NYU master's rows."""

    accepted_nyu_masters = and_(Applicant.status == "Accepted",
        func.lower(Applicant.llm_generated_university)
        == "new york university",
        Applicant.degree.ilike("Master%"))

    total_statement = select(count(Applicant.p_id)).where(
        accepted_nyu_masters)
    international_statement = select(count(Applicant.p_id)).where(
        and_(
            accepted_nyu_masters,
            Applicant.us_or_international == "International"))

    total_statement = total_statement.limit(clamp_query_limit(limit))
    total_count = session.scalar(total_statement) or 0
    international_statement = international_statement.limit(clamp_query_limit(limit))
    international_count = session.scalar(international_statement) or 0

    # Avoid dividing by zero if no matching NYU rows exist.
    if total_count == 0:
        return None

    return round(100 * international_count / total_count, 2)

def format_decimal(value, suffix=""):
    """Display missing results clearly and numeric results to two places."""
    if value is None:
        return "N/A"

    return f"{value:.2f}{suffix}"

def collect_orm_results(session: Session, limit=MAX_QUERY_LIMIT):
    """Collect the ORM answers shared by the webpage and command-line report."""
    results = {
        "fall_2026_count": question_1(session, limit=limit),
        "american_average_gpa": question_4(session, limit=limit),
        "fall_2025_acceptance_percentage": question_5(session, limit=limit),
        "raw_text_count": question_8(session, limit=limit),
        "llm_standardized_count": question_9(session, limit=limit),
        "nyu_international_percentage": question_10(session, limit=limit),
    }
    results["count_difference"] = results["llm_standardized_count"] - results["raw_text_count"]
    return results


def main():
    """Open one session and run the requested ORM questions in order."""
    with session_local() as session:
        results = collect_orm_results(session)

    print(f"1. Fall 2026 applicant count: {results['fall_2026_count']}")
    print(f"4. American Fall 2026 average GPA: {format_decimal(results['american_average_gpa'])}")
    print(
        "5. Fall 2025 acceptance percentage: "
        f"{format_decimal(results['fall_2025_acceptance_percentage'], '%')}"
    )
    print(f"8. Raw-text match count: {results['raw_text_count']}")
    print(
        f"9. LLM-standardized match count: {results['llm_standardized_count']} "
        f"LLM count minus raw-text count: {results['count_difference']}"
    )
    print(
        "10. International percentage among accepted NYU master's applicants: "
        f"{format_decimal(results['nyu_international_percentage'], '%')}"
    )

if __name__ == "__main__":
    main()
